name: 'setup-sqlcl'
description: 'Setup Oracle Sqlcl'
author: 'Christophe Pruvost @cpruvost'

runs:
  using: 'node12'
  main: 'dist/index.js'
  pre-if: 'runner.os == linux'

branding:
  icon: 'cloud'
  color: 'red'
