name: ci

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
         website: oracle.com
         release: 17    

      - run: java -version

      - name: Install Oracle Sqlcl
        uses: cpruvost/setup-sqlcl@main
        #with:
          #user: "${{ secrets.DB_USER }}"
          #password: "${{ secrets.DB_PASSWORD }}"
          #url: "${{ secrets.DB_URL }}"

      - run: |
          #./sqlcl/bin/sql -V
          sql -V
