name: test

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
         website: oracle.com
         release: 17    

      - run: java -version

      - name: Install Oracle Sqlcl
        uses: cpruvost/setup-sqlcl@main

      - run: |
          ./sqlcl/bin/sql -V
          exit | ./sqlcl/bin/sql ${{ secrets.DB_USER }}/${{ secrets.DB_PASSWORD }}@'${{  secrets.DB_URL }}' @./show_tables.sql
      
