name: ci

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Install Oracle Sqlcl
        uses: cpruvost/setup-sqlcl@main

      - run: sql -V -S
