name: ci

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Install Oracle Sqlcl
        uses: cpruvost/setup-sqlcl@main
        #with:
          #user: "${{ secrets.DB_USER }}"
          #password: "${{ secrets.DB_PASSWORD }}"
          #url: "${{ secrets.DB_URL }}"

      - run: sql '${{ secrets.DB_USER }}/${{ secrets.DB_PASSWORD }}@${{ secrets.DB_URL }}'
